spring.application.name=apartment-management

# Veritabanı Bağlantı Ayarları (Yerel Docker'daki SQL Server için)

# Docker'daki SQL Server'a yerel makinenizden bağlanmak için sunucu adresi 'localhost' veya 
# konteyner adını (eğer Docker network kullanıyorsanız) kullanırız.
# Port: 1433
spring.datasource.url=jdbc:sqlserver://localhost:1433;database=apartmentdb;encrypt=true;trustServerCertificate=true;
spring.datasource.user=sa
spring.datasource.password=Zzehra1234

# JDBC Driver Ayarları
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver